import{a as S,S as q,i as a}from"./assets/vendor-ClNNywv1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P="54345335-b1d733af450328b2a25aaa978",B="https://pixabay.com/api/";async function u(o,t=1){const s={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await S.get(B,{params:s})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".load-more"),f=document.querySelector(".loader");let M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${s}" alt="${e}" />
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </a>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",t),M.refresh()}function R(){m.innerHTML=""}function h(){f.classList.remove("hidden")}function y(){f.classList.add("hidden")}function b(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}let c="",l=1,d=0;const $=document.querySelector(".form"),O=document.querySelector(".load-more");$.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),!c){a.warning({message:"Please enter a search query!",position:"topRight"});return}l=1,R(),L(),h();try{const t=await u(c,l);d=Math.ceil(t.totalHits/15),t.hits.length===0?a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(g(t.hits),d>1?b():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){console.error(t),a.error({message:"Failed to fetch images. Please try again later!",position:"topRight"})}finally{y()}});O.addEventListener("click",async()=>{l+=1,L(),h();try{const o=await u(c,l);g(o.hits),l>=d?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b();const t=document.querySelector(".gallery-item");t&&window.scrollBy({top:t.getBoundingClientRect().height*2,behavior:"smooth"})}catch(o){console.error(o),a.error({message:"Something went wrong while loading more images!",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
