import{a as q,S as v,i as c}from"./assets/vendor-ClNNywv1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const B="54345335-b1d733af450328b2a25aaa978",M="https://pixabay.com/api/";async function f(r,t=1){const a={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await q.get(M,{params:a})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more");let P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:n,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${a}" alt="${e}" />
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </a>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",t),P.refresh()}function $(){m.innerHTML=""}function y(){g.classList.remove("hidden")}function b(){g.classList.add("hidden")}function L(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}let l="",s=1,u=0;const R=document.querySelector(".form"),x=document.querySelector(".load-more");R.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){c.warning({message:"Please enter a search query!",position:"topRight"});return}s=1,$(),d(),y();try{const t=await f(l,s);u=Math.ceil(t.totalHits/15),t.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",iconColor:"#fff",maxWidth:432}):(h(t.hits),s<u&&L())}catch{c.error({message:"Something went wrong!",position:"topRight"})}finally{b(),r.target.reset()}});x.addEventListener("click",async()=>{s+=1,d(),y();try{const r=await f(l,s);h(r.hits);const t=document.querySelector(".gallery-item");if(t){const a=t.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}s>=u?(d(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{c.error({message:"Failed to load more images!",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
